# CMake generated Testfile for 
# Source directory: D:/tuple/tests
# Build directory: D:/tuple/build_exp/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("D:/tuple/build_exp/tests/core_test[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_io_lexer[1]_include.cmake")
include("D:/tuple/build_exp/tests/solver_test[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_cost_table_io[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_solver_concepts[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_per_element_space[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_interval_split_space[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_other_spaces[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_cost_models[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_per_element_argmin[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_interval_dp[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_exhaustive_search[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_select_and_run[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_memo[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_space_parameterised[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_candidate_traversal[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_heterogeneous_space[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_constrained_search[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_constraints[1]_include.cmake")
include("D:/tuple/build_exp/tests/algebra_test[1]_include.cmake")
include("D:/tuple/build_exp/tests/graph_step1_test[1]_include.cmake")
include("D:/tuple/build_exp/tests/graph_step2_test[1]_include.cmake")
include("D:/tuple/build_exp/tests/graph_step3_test[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_graph_io[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_capacity_policy[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_deduction_aliases[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_io_layering[1]_include.cmake")
include("D:/tuple/build_exp/tests/graph_step5_test[1]_include.cmake")
include("D:/tuple/build_exp/tests/graph_step6_test[1]_include.cmake")
include("D:/tuple/build_exp/tests/graph_step7_test[1]_include.cmake")
include("D:/tuple/build_exp/tests/graph_hardening_test[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_symmetric_graph[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_graph_hardening_v2[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_graph_coloring[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_weighted_view[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_transforms[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_merge_rules[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_segmentation_dp[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_graph_umbrella[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_bipartite_matching[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_instantiation[1]_include.cmake")
include("D:/tuple/build_exp/tests/test_space_v072[1]_include.cmake")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_performance_models]=] "D:/tuple/build_exp/tests/Debug/test_performance_models.exe")
  set_tests_properties([=[test_performance_models]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;128;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_performance_models]=] "D:/tuple/build_exp/tests/Release/test_performance_models.exe")
  set_tests_properties([=[test_performance_models]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;128;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_performance_models]=] "D:/tuple/build_exp/tests/MinSizeRel/test_performance_models.exe")
  set_tests_properties([=[test_performance_models]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;128;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_performance_models]=] "D:/tuple/build_exp/tests/RelWithDebInfo/test_performance_models.exe")
  set_tests_properties([=[test_performance_models]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;128;add_test;D:/tuple/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_performance_models]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_perf_counter]=] "D:/tuple/build_exp/tests/Debug/test_perf_counter.exe")
  set_tests_properties([=[test_perf_counter]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;151;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_perf_counter]=] "D:/tuple/build_exp/tests/Release/test_perf_counter.exe")
  set_tests_properties([=[test_perf_counter]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;151;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_perf_counter]=] "D:/tuple/build_exp/tests/MinSizeRel/test_perf_counter.exe")
  set_tests_properties([=[test_perf_counter]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;151;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_perf_counter]=] "D:/tuple/build_exp/tests/RelWithDebInfo/test_perf_counter.exe")
  set_tests_properties([=[test_perf_counter]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;151;add_test;D:/tuple/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_perf_counter]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_fix_bench]=] "D:/tuple/build_exp/tests/Debug/test_fix_bench.exe")
  set_tests_properties([=[test_fix_bench]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;204;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_fix_bench]=] "D:/tuple/build_exp/tests/Release/test_fix_bench.exe")
  set_tests_properties([=[test_fix_bench]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;204;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_fix_bench]=] "D:/tuple/build_exp/tests/MinSizeRel/test_fix_bench.exe")
  set_tests_properties([=[test_fix_bench]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;204;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_fix_bench]=] "D:/tuple/build_exp/tests/RelWithDebInfo/test_fix_bench.exe")
  set_tests_properties([=[test_fix_bench]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;204;add_test;D:/tuple/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_fix_bench]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_fix_dp_search]=] "D:/tuple/build_exp/tests/Debug/test_fix_dp_search.exe")
  set_tests_properties([=[test_fix_dp_search]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;209;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_fix_dp_search]=] "D:/tuple/build_exp/tests/Release/test_fix_dp_search.exe")
  set_tests_properties([=[test_fix_dp_search]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;209;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_fix_dp_search]=] "D:/tuple/build_exp/tests/MinSizeRel/test_fix_dp_search.exe")
  set_tests_properties([=[test_fix_dp_search]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;209;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_fix_dp_search]=] "D:/tuple/build_exp/tests/RelWithDebInfo/test_fix_dp_search.exe")
  set_tests_properties([=[test_fix_dp_search]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;209;add_test;D:/tuple/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_fix_dp_search]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_phase2_strategies]=] "D:/tuple/build_exp/tests/Debug/test_phase2_strategies.exe")
  set_tests_properties([=[test_phase2_strategies]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;214;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_phase2_strategies]=] "D:/tuple/build_exp/tests/Release/test_phase2_strategies.exe")
  set_tests_properties([=[test_phase2_strategies]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;214;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_phase2_strategies]=] "D:/tuple/build_exp/tests/MinSizeRel/test_phase2_strategies.exe")
  set_tests_properties([=[test_phase2_strategies]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;214;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_phase2_strategies]=] "D:/tuple/build_exp/tests/RelWithDebInfo/test_phase2_strategies.exe")
  set_tests_properties([=[test_phase2_strategies]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;214;add_test;D:/tuple/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_phase2_strategies]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_phase3_fix_calibration]=] "D:/tuple/build_exp/tests/Debug/test_phase3_fix_calibration.exe")
  set_tests_properties([=[test_phase3_fix_calibration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;227;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_phase3_fix_calibration]=] "D:/tuple/build_exp/tests/Release/test_phase3_fix_calibration.exe")
  set_tests_properties([=[test_phase3_fix_calibration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;227;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[test_phase3_fix_calibration]=] "D:/tuple/build_exp/tests/MinSizeRel/test_phase3_fix_calibration.exe")
  set_tests_properties([=[test_phase3_fix_calibration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;227;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_phase3_fix_calibration]=] "D:/tuple/build_exp/tests/RelWithDebInfo/test_phase3_fix_calibration.exe")
  set_tests_properties([=[test_phase3_fix_calibration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;227;add_test;D:/tuple/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_phase3_fix_calibration]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[ctdp_calibration_test]=] "D:/tuple/build_exp/tests/Debug/ctdp_calibration_test.exe")
  set_tests_properties([=[ctdp_calibration_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;255;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[ctdp_calibration_test]=] "D:/tuple/build_exp/tests/Release/ctdp_calibration_test.exe")
  set_tests_properties([=[ctdp_calibration_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;255;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[ctdp_calibration_test]=] "D:/tuple/build_exp/tests/MinSizeRel/ctdp_calibration_test.exe")
  set_tests_properties([=[ctdp_calibration_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;255;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[ctdp_calibration_test]=] "D:/tuple/build_exp/tests/RelWithDebInfo/ctdp_calibration_test.exe")
  set_tests_properties([=[ctdp_calibration_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;255;add_test;D:/tuple/tests/CMakeLists.txt;0;")
else()
  add_test([=[ctdp_calibration_test]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[ctdp_phase3_test]=] "D:/tuple/build_exp/tests/Debug/ctdp_phase3_test.exe")
  set_tests_properties([=[ctdp_phase3_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;255;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[ctdp_phase3_test]=] "D:/tuple/build_exp/tests/Release/ctdp_phase3_test.exe")
  set_tests_properties([=[ctdp_phase3_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;255;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[ctdp_phase3_test]=] "D:/tuple/build_exp/tests/MinSizeRel/ctdp_phase3_test.exe")
  set_tests_properties([=[ctdp_phase3_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;255;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[ctdp_phase3_test]=] "D:/tuple/build_exp/tests/RelWithDebInfo/ctdp_phase3_test.exe")
  set_tests_properties([=[ctdp_phase3_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;255;add_test;D:/tuple/tests/CMakeLists.txt;0;")
else()
  add_test([=[ctdp_phase3_test]=] NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[ctdp_phase6_test]=] "D:/tuple/build_exp/tests/Debug/ctdp_phase6_test.exe")
  set_tests_properties([=[ctdp_phase6_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;255;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[ctdp_phase6_test]=] "D:/tuple/build_exp/tests/Release/ctdp_phase6_test.exe")
  set_tests_properties([=[ctdp_phase6_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;255;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[ctdp_phase6_test]=] "D:/tuple/build_exp/tests/MinSizeRel/ctdp_phase6_test.exe")
  set_tests_properties([=[ctdp_phase6_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;255;add_test;D:/tuple/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[ctdp_phase6_test]=] "D:/tuple/build_exp/tests/RelWithDebInfo/ctdp_phase6_test.exe")
  set_tests_properties([=[ctdp_phase6_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/tuple/tests/CMakeLists.txt;255;add_test;D:/tuple/tests/CMakeLists.txt;0;")
else()
  add_test([=[ctdp_phase6_test]=] NOT_AVAILABLE)
endif()
subdirs("../_deps/googletest-build")
