if(EXISTS "D:/tuple/build_exp/tests/test_interval_dp[1]_tests.cmake")
  include("D:/tuple/build_exp/tests/test_interval_dp[1]_tests.cmake")
else()
  add_test(test_interval_dp_NOT_BUILT test_interval_dp_NOT_BUILT)
endif()
