if(EXISTS "D:/tuple/build_exp/tests/test_segmentation_dp[1]_tests.cmake")
  include("D:/tuple/build_exp/tests/test_segmentation_dp[1]_tests.cmake")
else()
  add_test(test_segmentation_dp_NOT_BUILT test_segmentation_dp_NOT_BUILT)
endif()
