if(EXISTS "D:/tuple/build_exp/tests/test_constraints[1]_tests.cmake")
  include("D:/tuple/build_exp/tests/test_constraints[1]_tests.cmake")
else()
  add_test(test_constraints_NOT_BUILT test_constraints_NOT_BUILT)
endif()
