if(EXISTS "D:/tuple/build_exp/tests/test_select_and_run[1]_tests.cmake")
  include("D:/tuple/build_exp/tests/test_select_and_run[1]_tests.cmake")
else()
  add_test(test_select_and_run_NOT_BUILT test_select_and_run_NOT_BUILT)
endif()
