if(EXISTS "D:/tuple/build_exp/tests/test_heterogeneous_space[1]_tests.cmake")
  include("D:/tuple/build_exp/tests/test_heterogeneous_space[1]_tests.cmake")
else()
  add_test(test_heterogeneous_space_NOT_BUILT test_heterogeneous_space_NOT_BUILT)
endif()
