if(EXISTS "D:/tuple/build_exp/tests/test_cost_table_io[1]_tests.cmake")
  include("D:/tuple/build_exp/tests/test_cost_table_io[1]_tests.cmake")
else()
  add_test(test_cost_table_io_NOT_BUILT test_cost_table_io_NOT_BUILT)
endif()
