if(EXISTS "D:/tuple/build_exp/tests/test_io_lexer[1]_tests.cmake")
  include("D:/tuple/build_exp/tests/test_io_lexer[1]_tests.cmake")
else()
  add_test(test_io_lexer_NOT_BUILT test_io_lexer_NOT_BUILT)
endif()
