if(EXISTS "D:/tuple/build_exp/tests/test_merge_rules[1]_tests.cmake")
  include("D:/tuple/build_exp/tests/test_merge_rules[1]_tests.cmake")
else()
  add_test(test_merge_rules_NOT_BUILT test_merge_rules_NOT_BUILT)
endif()
