if(EXISTS "D:/tuple/build_exp/tests/test_graph_io[1]_tests.cmake")
  include("D:/tuple/build_exp/tests/test_graph_io[1]_tests.cmake")
else()
  add_test(test_graph_io_NOT_BUILT test_graph_io_NOT_BUILT)
endif()
