if(EXISTS "D:/tuple/build_exp/tests/test_deduction_aliases[1]_tests.cmake")
  include("D:/tuple/build_exp/tests/test_deduction_aliases[1]_tests.cmake")
else()
  add_test(test_deduction_aliases_NOT_BUILT test_deduction_aliases_NOT_BUILT)
endif()
