if(EXISTS "D:/tuple/build_exp/tests/test_capacity_policy[1]_tests.cmake")
  include("D:/tuple/build_exp/tests/test_capacity_policy[1]_tests.cmake")
else()
  add_test(test_capacity_policy_NOT_BUILT test_capacity_policy_NOT_BUILT)
endif()
