if(EXISTS "D:/tuple/build_exp/tests/test_per_element_argmin[1]_tests.cmake")
  include("D:/tuple/build_exp/tests/test_per_element_argmin[1]_tests.cmake")
else()
  add_test(test_per_element_argmin_NOT_BUILT test_per_element_argmin_NOT_BUILT)
endif()
