#ifndef CTDP_CALIBRATOR_CT_DP_EMIT_H
#define CTDP_CALIBRATOR_CT_DP_EMIT_H

// ctdp::calibrator::ct_dp_emit — Emit constexpr headers from profiles
//
// Design v2.2 §5.6:
//   Emits constexpr headers from fitted profiles. The emitted header
//   encodes the Callable identity as a type alias or tag so that the
//   solver can verify compatibility at compile time.
//
// This is the "wisdom file" in C++ form — the bridge from runtime
// calibration to compile-time optimisation.
//
// The emitted header contains:
//   - A constexpr lookup table (for lookup profiles)
//   - Constexpr linear coefficients (for linear profiles)
//   - Type aliases for Space and Callable identity
//   - Provenance comments for reproducibility
//
// Usage:
//   auto profile = fit_lookup_profile(dataset);
//   std::ofstream out("parser_profile.h");
//   emit_constexpr_profile(out, profile, "fix_swar_parser_profile");

#include "calibration_profile.h"

#include <cstddef>
#include <iomanip>
#include <ostream>
#include <string>
#include <string_view>

namespace ctdp::calibrator {

// ─── Constexpr emission ──────────────────────────────────────────

/// Emit a lookup profile as a constexpr C++ header.
///
/// The emitted code contains:
///   - Provenance as comments
///   - A constexpr struct with a predict() method
///   - A constexpr instance named `variable_name`
///
/// @param os             Output stream
/// @param profile        The fitted lookup profile
/// @param variable_name  Name for the constexpr variable
/// @param space_type_str String representation of the Space type
/// @param callable_str   String representation of the Callable type
///
template <typename Space, typename Callable>
void emit_constexpr_lookup(
    std::ostream& os,
    calibration_profile<Space, Callable> const& profile,
    std::string_view variable_name,
    std::string_view space_type_str,
    std::string_view callable_str)
{
    auto const& prov = profile.provenance;

    // Header guard
    std::string guard = "CTDP_GENERATED_";
    for (char c : variable_name) {
        guard += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    }
    guard += "_H";

    os << "#ifndef " << guard << "\n";
    os << "#define " << guard << "\n\n";

    // Provenance comments
    os << "// Auto-generated by ctdp::calibrator::ct_dp_emit\n";
    os << "// DO NOT EDIT — regenerate from calibration data.\n";
    os << "//\n";
    os << "// Scenario:   " << prov.scenario_name << "\n";
    os << "// Callable:   " << callable_str << "\n";
    os << "// Timestamp:  " << prov.timestamp << "\n";
    os << "// CPU:        " << prov.cpu_model << "\n";
    os << "// Compiler:   " << prov.compiler << "\n";
    os << "// Points:     " << profile.training_points << "\n";
    os << "//\n\n";

    os << "#include <array>\n";
    os << "#include <cstddef>\n";
    os << "#include <utility>\n\n";

    os << "namespace ctdp::generated {\n\n";

    // Type aliases for identity verification
    os << "// Type identity (for compile-time verification)\n";
    os << "// using space_type    = " << space_type_str << ";\n";
    os << "// using callable_type = " << callable_str << ";\n\n";

    // The lookup table
    auto const& entries = profile.lookup.entries;
    os << "struct " << variable_name << "_t {\n";
    os << "    static constexpr std::size_t N = "
       << entries.size() << ";\n\n";

    // Emit as parallel arrays (point index → cost)
    // For constexpr usage, costs are stored as a simple array.
    os << "    // Lookup table: index → cost (ns)\n";
    os << "    static constexpr std::array<double, N> costs = {{\n";
    for (std::size_t i = 0; i < entries.size(); ++i) {
        os << "        " << std::fixed << std::setprecision(2)
           << entries[i].second;
        if (i + 1 < entries.size()) os << ",";
        os << "\n";
    }
    os << "    }};\n\n";

    // constexpr predict by index
    os << "    [[nodiscard]] static constexpr double predict(std::size_t index) noexcept {\n";
    os << "        return (index < N) ? costs[index] : -1.0;\n";
    os << "    }\n";
    os << "};\n\n";

    os << "inline constexpr " << variable_name << "_t "
       << variable_name << "{};\n\n";

    os << "} // namespace ctdp::generated\n\n";
    os << "#endif // " << guard << "\n";
}

/// Emit a linear profile as a constexpr C++ header.
///
template <typename Space, typename Callable>
void emit_constexpr_linear(
    std::ostream& os,
    calibration_profile<Space, Callable> const& profile,
    std::string_view variable_name,
    std::string_view space_type_str,
    std::string_view callable_str)
{
    auto const& prov = profile.provenance;
    auto const& coeffs = profile.linear_coefficients;

    std::string guard = "CTDP_GENERATED_";
    for (char c : variable_name) {
        guard += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    }
    guard += "_H";

    os << "#ifndef " << guard << "\n";
    os << "#define " << guard << "\n\n";

    os << "// Auto-generated by ctdp::calibrator::ct_dp_emit\n";
    os << "// DO NOT EDIT — regenerate from calibration data.\n";
    os << "//\n";
    os << "// Scenario:   " << prov.scenario_name << "\n";
    os << "// Callable:   " << callable_str << "\n";
    os << "// Timestamp:  " << prov.timestamp << "\n";
    os << "// R²:         " << std::fixed << std::setprecision(6)
       << profile.linear_r_squared << "\n";
    os << "// Points:     " << profile.training_points << "\n";
    os << "//\n\n";

    os << "#include <array>\n";
    os << "#include <cstddef>\n\n";

    os << "namespace ctdp::generated {\n\n";

    os << "// Type identity\n";
    os << "// using space_type    = " << space_type_str << ";\n";
    os << "// using callable_type = " << callable_str << ";\n\n";

    os << "struct " << variable_name << "_t {\n";
    os << "    static constexpr std::size_t num_features = "
       << coeffs.size() << ";\n\n";

    os << "    static constexpr double intercept = "
       << std::fixed << std::setprecision(6) << profile.linear_intercept
       << ";\n\n";

    os << "    static constexpr std::array<double, num_features> coefficients = {{\n";
    for (std::size_t i = 0; i < coeffs.size(); ++i) {
        os << "        " << std::fixed << std::setprecision(6) << coeffs[i];
        if (i + 1 < coeffs.size()) os << ",";
        os << "\n";
    }
    os << "    }};\n\n";

    os << "    static constexpr double r_squared = "
       << std::fixed << std::setprecision(6) << profile.linear_r_squared
       << ";\n\n";

    os << "    /// Predict cost from features\n";
    os << "    [[nodiscard]] static constexpr double predict(\n";
    os << "        std::array<float, num_features> const& features) noexcept\n";
    os << "    {\n";
    os << "        double y = intercept;\n";
    os << "        for (std::size_t i = 0; i < num_features; ++i) {\n";
    os << "            y += coefficients[i] * static_cast<double>(features[i]);\n";
    os << "        }\n";
    os << "        return y;\n";
    os << "    }\n";
    os << "};\n\n";

    os << "inline constexpr " << variable_name << "_t "
       << variable_name << "{};\n\n";

    os << "} // namespace ctdp::generated\n\n";
    os << "#endif // " << guard << "\n";
}

/// Emit a profile as constexpr, dispatching on active_model.
template <typename Space, typename Callable>
void emit_constexpr_profile(
    std::ostream& os,
    calibration_profile<Space, Callable> const& profile,
    std::string_view variable_name,
    std::string_view space_type_str = "/* Space */",
    std::string_view callable_str  = "/* Callable */")
{
    using mt = typename calibration_profile<Space, Callable>::model_type;
    switch (profile.active_model) {
        case mt::lookup:
            emit_constexpr_lookup(os, profile, variable_name,
                                  space_type_str, callable_str);
            break;
        case mt::linear:
            emit_constexpr_linear(os, profile, variable_name,
                                  space_type_str, callable_str);
            break;
        case mt::none:
            os << "// ERROR: no fitted model to emit\n";
            break;
    }
}

} // namespace ctdp::calibrator

#endif // CTDP_CALIBRATOR_CT_DP_EMIT_H
