#ifndef CTDP_CALIBRATOR_PLAN_EMIT_H
#define CTDP_CALIBRATOR_PLAN_EMIT_H

// ctdp::calibrator::plan_emit — Emit plans as constexpr C++ headers
//
// Extends ct_dp_emit.h to operate on plan<Space, Callable> rather
// than calibration_profile.  The emitted header encodes the full
// solver output: ranked entries, costs, objectives, Pareto status.
//
// The emitted code can be #include'd to make plan data available
// as constexpr arrays at compile time — the FFTW "wisdom" pattern
// applied to C++ template instantiation.
//
// Usage:
//   auto plan = build_plan(profile, scenario);
//   std::ofstream f("parser_plan.h");
//   emit_plan_header(f, plan, "parser_plan",
//       "parser_space", "integer_parser_tag",
//       [](auto const& pt) {
//           return "{" + std::to_string(pt.digits) + ", "
//                  + std::to_string(static_cast<int>(pt.strategy)) + "}";
//       });

#include "plan.h"
#include "provenance.h"

#include <cstddef>
#include <cstdio>
#include <functional>
#include <ostream>
#include <string>
#include <string_view>

namespace ctdp::calibrator {

// ─── Point serialiser concept ────────────────────────────────────

/// A PointSerialiser converts a point to a C++ brace-init expression.
/// e.g., "{3, parse_strategy::swar}" or "{1024, 64}"
template <typename S, typename PointType>
concept PointSerialiser = requires(S const& s, PointType const& pt) {
    { s(pt) } -> std::convertible_to<std::string>;
};

// ─── Default serialiser (for simple arithmetic types) ────────────

/// Default: emits a comment placeholder.  Users should provide
/// a domain-specific serialiser for their point types.
struct default_point_serialiser {
    template <typename PointType>
    std::string operator()(PointType const&) const {
        return "{}  /* provide PointSerialiser for actual values */";
    }
};

// ─── Plan emission ───────────────────────────────────────────────

/// Emit a plan as a constexpr C++ header.
///
/// @param out          Output stream
/// @param p            The plan to emit
/// @param name         Variable name prefix
/// @param space_name   C++ type name for Space
/// @param callable_name C++ type name for Callable
/// @param serialiser   Converts point_type → C++ brace expression
///
/// Emits:
///   - Header guard
///   - Provenance comment
///   - constexpr array of {point, cost_ns} entries (sorted by cost)
///   - constexpr optimal point/cost accessors
///   - Pareto frontier array (if multi-objective)
///
template <typename Space, typename Callable, typename Serialiser>
    requires PointSerialiser<Serialiser, typename Space::point_type>
void emit_plan_header(
    std::ostream& out,
    plan<Space, Callable> const& p,
    std::string_view name,
    std::string_view space_name,
    std::string_view callable_name,
    Serialiser const& serialiser)
{
    auto guard = std::string("CTDP_WISDOM_") + std::string(name) + "_H";
    for (auto& c : guard) {
        if (c >= 'a' && c <= 'z') c = static_cast<char>(c - 32);
        if (c == ' ' || c == '-' || c == '.') c = '_';
    }

    out << "// Auto-generated by ctdp::calibrator::emit_plan_header\n";
    out << "// Solver: " << p.solver_name << "\n";
    if (!p.provenance.scenario_name.empty()) {
        out << "// Scenario: " << p.provenance.scenario_name << "\n";
    }
    if (!p.provenance.hostname.empty()) {
        out << "// Platform: " << p.provenance.hostname << "\n";
    }
    if (!p.provenance.compiler.empty()) {
        out << "// Compiler: " << p.provenance.compiler << "\n";
    }
    out << "// Points evaluated: " << p.evaluated_points << "\n";
    out << "// Plan entries: " << p.entries.size() << "\n";
    out << "//\n";
    out << "// Space:    " << space_name << "\n";
    out << "// Callable: " << callable_name << "\n";
    out << "\n";
    out << "#ifndef " << guard << "\n";
    out << "#define " << guard << "\n\n";

    out << "#include <array>\n";
    out << "#include <cstddef>\n\n";

    out << "namespace ctdp::wisdom {\n\n";

    // ─── Entry struct ────────────────────────────────────────────
    out << "struct " << name << "_entry {\n";
    out << "    double cost_ns;\n";
    out << "    bool   pareto_optimal;\n";
    out << "};\n\n";

    // ─── Plan entries (cost + Pareto flag) ───────────────────────
    out << "// Entries sorted by cost ascending (N = "
        << p.entries.size() << ")\n";
    out << "inline constexpr std::size_t " << name
        << "_N = " << p.entries.size() << ";\n\n";

    out << "inline constexpr std::array<" << name << "_entry, "
        << name << "_N> " << name << "_entries = {{\n";
    for (std::size_t i = 0; i < p.entries.size(); ++i) {
        auto const& e = p.entries[i];
        char buf[128];
        std::snprintf(buf, sizeof(buf),
            "    {%.6f, %s}",
            e.cost_ns,
            e.pareto_optimal ? "true" : "false");
        out << buf;
        if (i + 1 < p.entries.size()) out << ",";
        out << "  // rank " << i << ": " << serialiser(e.point) << "\n";
    }
    out << "}};\n\n";

    // ─── Point array (separate for type safety) ──────────────────
    out << "// Point values (matches entries array by index)\n";
    out << "// Point type: " << space_name << "::point_type\n";
    out << "// Each point serialised by user-provided PointSerialiser.\n";
    out << "//\n";
    out << "// To use: define your point_type and uncomment:\n";
    out << "//\n";
    out << "// inline constexpr std::array<point_type, "
        << name << "_N> " << name << "_points = {{\n";
    for (std::size_t i = 0; i < p.entries.size(); ++i) {
        out << "//     " << serialiser(p.entries[i].point);
        if (i + 1 < p.entries.size()) out << ",";
        out << "\n";
    }
    out << "// }};\n\n";

    // ─── Optimal accessors ───────────────────────────────────────
    if (!p.entries.empty()) {
        char buf[128];
        std::snprintf(buf, sizeof(buf),
            "inline constexpr double %.*s_optimal_cost = %.6f;\n",
            static_cast<int>(name.size()), name.data(),
            p.entries.front().cost_ns);
        out << buf;
        out << "inline constexpr std::size_t " << name
            << "_optimal_rank = 0;\n\n";
    }

    // ─── Pareto frontier summary ─────────────────────────────────
    std::size_t pareto_count = 0;
    for (auto const& e : p.entries) {
        if (e.pareto_optimal) ++pareto_count;
    }
    if (pareto_count > 0) {
        out << "// Pareto frontier: " << pareto_count << " non-dominated point(s)\n";
        out << "inline constexpr std::size_t " << name
            << "_pareto_count = " << pareto_count << ";\n\n";
    }

    // ─── Solver metadata ─────────────────────────────────────────
    out << "inline constexpr const char* " << name
        << "_solver = \"" << p.solver_name << "\";\n";
    out << "inline constexpr std::size_t " << name
        << "_evaluated = " << p.evaluated_points << ";\n\n";

    // ─── Lookup helper ───────────────────────────────────────────
    out << "/// Predict cost for rank index.  Returns -1.0 if out of range.\n";
    out << "[[nodiscard]] constexpr double " << name
        << "_predict(std::size_t rank) noexcept {\n";
    out << "    if (rank >= " << name << "_N) return -1.0;\n";
    out << "    return " << name << "_entries[rank].cost_ns;\n";
    out << "}\n\n";

    out << "} // namespace ctdp::wisdom\n\n";
    out << "#endif // " << guard << "\n";
}

/// Convenience overload with default serialiser.
template <typename Space, typename Callable>
void emit_plan_header(
    std::ostream& out,
    plan<Space, Callable> const& p,
    std::string_view name,
    std::string_view space_name,
    std::string_view callable_name)
{
    emit_plan_header(out, p, name, space_name, callable_name,
                     default_point_serialiser{});
}

} // namespace ctdp::calibrator

#endif // CTDP_CALIBRATOR_PLAN_EMIT_H
